CREATE DATABASE LIBRARY
GO

USE LIBRARY

CREATE TABLE [PERSONAS](--OBLIGATORIO
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED ([ID]),
	[CEDULA] BIGINT NOT NULL UNIQUE,--OBLIGATORIO
	[NOMBRE] VARCHAR(80)NOT NULL,
	[NUMERO] BIGINT,--OBLIGATORIO (NUMERO)
);

/*CREATE TABLE [AUTORES](
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_AUTORES] PRIMARY KEY CLUSTERED ([ID]),
	[SEUDONIMO] VARCHAR(40),
	--PAIS_ORIGEN VARCHAR(50),
);*/

CREATE TABLE [USUARIOS](--OBLIGATORIO
	[COD_USUARIO] INT NOT NULL UNIQUE,--OBLIGATORIO
	CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED ([COD_USUARIO]),
	[CORREO] VARCHAR(40) NOT NULL,
	[CONTRASEÑA] VARCHAR(20)NOT NULL,
	[PERSONA] INT,
	CONSTRAINT [FK_AUTORES_LIBROS] FOREIGN KEY ([PERSONA]) REFERENCES [PERSONAS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);

/*CREATE TABLE [CATEGORIAS](
	[ID] INT NOT NULL IDENTITY (1, 1),
	[NOMBRE] VARCHAR(40),
	[DESCRIPCION] VARCHAR(50),
	CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY CLUSTERED ([ID]),
);*/

CREATE TABLE [LIBROS](
	[ID] INT NOT NULL IDENTITY(1,1),
	CONSTRAINT [PK_LIBROS] PRIMARY KEY CLUSTERED ([ID]),
	[COD_LIBRO] INT NOT NULL UNIQUE,--OBLIGATORIO
	[NOMBRE_LIBRO] VARCHAR(30) NOT NULL,--OBLIGATORIO 
	[FECHA_PUBLICACION] DATE,
	[AUTOR] VARCHAR(40)
);

/*CREATE TABLE [LIBRO_AUTOR](
	[LIBRO] INT NOT NULL,
	[AUTOR] INT NOT NULL,
	CONSTRAINT [FK_AUTORES_LIBROS] FOREIGN KEY ([LIBRO]) REFERENCES [LIBROS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_LIBROS_AUTORES] FOREIGN KEY ([AUTOR]) REFERENCES [AUTORES] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);*/

CREATE TABLE [COPIAS](
	[ID] INT NOT NULL IDENTITY (1, 1),
	CONSTRAINT [PK_COPIAS] PRIMARY KEY CLUSTERED ([ID]),
	[NOTAS] VARCHAR(55),	--[NOTAS_ESTADO] VARCHAR(55),--OBLIGATORIO
	[ESTADO] BIT DEFAULT 0,--OBLIGATORIO
	[LIBRO] INT,
	CONSTRAINT [FK_COPIAS_LIBROS] FOREIGN KEY ([LIBRO]) REFERENCES [LIBROS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE [PRESTAMOS](
	[ID] INT NOT NULL IDENTITY (1, 1),
	CONSTRAINT [PK_PRESTAMOS] PRIMARY KEY CLUSTERED ([ID]),
	[FECHA_INICIO] DATE NOT NULL,--OBLIGATORIO
	[USUARIO] INT,
	CONSTRAINT [FK_PRESTAMOS_USUARIOS] FOREIGN KEY ([USUARIO]) REFERENCES [USUARIOS] ([COD_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE [DETALLES](
	[ID] INT NOT NULL IDENTITY (1, 1),
	CONSTRAINT [PK_DETALLES] PRIMARY KEY CLUSTERED ([ID]),
	[FECHA_FINAL] DATE NOT NULL,--OBLIGATORIO
	[PRESTAMO] INT NOT NULL,
	[COPIA] INT NOT NULL,
	CONSTRAINT [FK_DETALLES_PRESTAMOS] FOREIGN KEY ([PRESTAMO]) REFERENCES [PRESTAMOS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_DETALLES_COPIAS] FOREIGN KEY ([COPIA]) REFERENCES [COPIAS] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
)

INSERT INTO [PERSONAS]([CEDULA],[NOMBRE],[NUMERO]) VALUES
(15123,'Esteban Quintero Yepes',312344874),
(51232,'Juan Esteban Zapata Yepes',5324354646),
(23433,'Esteban David Quintero Puerta',23435464),
(65413,'Esteban Emanuel Quintero Yepes',685639844),
(76454,'Angie Esteban Quintero',312344876)
SELECT * FROM [PERSONAS]

/*INSERT INTO [AUTORES]([SEUDONIMO])VALUES
('Silleban'),
('Nevereban'),
('Noseban'),
('Guerrilleban'),
('Mariguneban')
SELECT * FROM [AUTORES]*/

/*INSERT INTO [AUTORES]([CODIGO_AUTOR],[SEUDONIMO],PAIS_ORIGEN)VALUES
(65427,'Silleban','Medellín'),
(9876,'Nevereban','Bogota'),
(098756,'Noseban','Bello'),
(98765,'Guerrilleban','Cali'),
(876502,'Mariguneban','Popayan')
SELECT * FROM [AUTORES]*/

INSERT INTO [USUARIOS]([COD_USUARIO],[CORREO],[CONTRASEÑA],[PERSONA])VALUES
(235765,'Example@correo.com','Holamundo',2),
(543214,'Example@correo.com','Holam',1),
(6543269,'Example@correo.com','Holapa',3),
(9005566,'Example@correo.com','Holasugra',4),
(987653,'Example@correo.com','Holainfiel',5)
SELECT * FROM [USUARIOS]

/*INSERT INTO [CATEGORIAS] ([NOMBRE],[DESCRIPCION]) VALUES
('Terror','Mucho Terror'),
('Accion','Mucho Accion'),
('Comedia','Mucho Comedia'),
('Suspenso','Mucho Suspenso'),
('Drama','Mucho Drama')
SELECT * FROM [CATEGORIAS]*/

INSERT INTO [LIBROS]([COD_LIBRO],[NOMBRE_LIBRO],[FECHA_PUBLICACION],[AUTOR]) VALUES
(23468,'Titulo1','1930-11-01','Silleban'),
(12454,'Titulo2','1920-12-10','Nevereban'),
(965594,'Titulo3','1910-09-21','Noseban'),
(10872,'Titulo4','1940-07-23','Guerrilleban'),
(874723,'Titulo5','1950-07-22','Mariguneban')
SELECT * FROM [LIBROS]

/*INSERT INTO [LIBRO_AUTOR]([LIBRO],[AUTOR])VALUES
(001,1),
(002,2),
(003,2),
(004,3),
(005,4),
(005,5)
SELECT * FROM [LIBRO_AUTOR]*/

INSERT INTO [COPIAS]([NOTAS],[ESTADO],[LIBRO])VALUES
('A',1,1),
('T',0,2),
('H',1,5),
('J',0,2),
('K',1,3),
('C',1,3)
SELECT * FROM [COPIAS]

INSERT INTO [PRESTAMOS]([FECHA_INICIO],[USUARIO])VALUES
('1530-11-01',235765),
('1730-11-01',7632423),
('1330-11-01',76325436),
('1230-11-01',6436756),
('1130-11-01',6436756),
('1030-11-01',76325436)
SELECT * FROM [PRESTAMOS]

INSERT INTO [DETALLES]([FECHA_FINAL],[PRESTAMO],[COPIA])VALUES
('2002-03-15',1,4),
('1980-03-25',1,3),
('2002-11-15',3,2),
('1850-03-25',5,2),
('1980-03-25',4,5),
('2001-12-12',3,7)
SELECT * FROM [DETALLES]